
//Generated by OSDMaker for the Quantracker Air OSD
//https://github.com/kwikius/quantracker
//https://github.com/kwikius/osd_maker

#include <quan/uav/osd/api.hpp>
#include <quan/uav/osd/basic_bitmap.hpp>

namespace {

 struct home_arrow_type : quan::uav::osd::basic_bitmap{
    uint8_t const * get_data()const
    {
       return m_data;
    }
    quan::uav::osd::size_type get_size()const
    {
       return {21,27};
    }
 private:
    static constexpr uint8_t m_data[142] = {
      255, 255, 171, 255
      , 255, 255, 255, 111
      , 254, 255, 255, 255
      , 175, 233, 255, 255
      , 255, 191, 149, 255
      , 255, 255, 191, 86
      , 250, 255, 255, 255
      , 86, 229, 255, 255
      , 255, 90, 149, 254
      , 255, 255, 91, 85
      , 249, 255, 255, 107
      , 85, 165, 255, 255
      , 111, 85, 85, 254
      , 255, 175, 85, 85
      , 233, 255, 191, 85
      , 85, 149, 255, 191
      , 86, 85, 85, 250
      , 255, 86, 165, 86
      , 229, 255, 90, 149
      , 90, 149, 254, 91
      , 149, 174, 85, 249
      , 107, 85, 254, 86
      , 165, 111, 85, 250
      , 107, 85, 174, 85
      , 249, 191, 85, 169
      , 85, 233, 255, 90
      , 149, 86, 229, 255
      , 111, 85, 170, 165
      , 255, 255, 150, 250
      , 170, 255, 255, 171
      , 254, 255, 255, 255
      , 255, 255, 255, 255
      , 255, 255, 255, 255
      , 255, 255, 255, 255
      , 255, 255, 255, 255
      , 255, 255
      };
   } home_arrow;
  constexpr uint8_t home_arrow_type::m_data [ 142];

 struct home_image_type : quan::uav::osd::basic_bitmap{
    uint8_t const * get_data()const
    {
       return m_data;
    }
    quan::uav::osd::size_type get_size()const
    {
       return {20,19};
    }
 private:
    static constexpr uint8_t m_data[95] = {
      255, 255, 235, 255
      , 255, 255, 191, 150
      , 254, 255, 255, 107
      , 105, 233, 255, 191
      , 150, 150, 150, 254
      , 107, 105, 85, 105
      , 233, 150, 86, 85
      , 149, 150, 106, 85
      , 85, 85, 169, 111
      , 85, 149, 170, 249
      , 111, 85, 149, 128
      , 249, 111, 169, 154
      , 128, 249, 111, 9
      , 152, 128, 249, 111
      , 9, 152, 128, 249
      , 111, 9, 152, 170
      , 249, 111, 9, 88
      , 85, 249, 111, 9
      , 88, 85, 249, 111
      , 9, 88, 85, 249
      , 111, 9, 88, 85
      , 249, 111, 9, 88
      , 85, 249, 175, 170
      , 170, 170, 250
      };
   } home_image;
  constexpr uint8_t home_image_type::m_data [ 95];

 struct satellite_image_type : quan::uav::osd::basic_bitmap{
    uint8_t const * get_data()const
    {
       return m_data;
    }
    quan::uav::osd::size_type get_size()const
    {
       return {15,19};
    }
 private:
    static constexpr uint8_t m_data[72] = {
      175, 234, 255, 255
      , 90, 233, 175, 175
      , 169, 229, 150, 91
      , 170, 166, 229, 150
      , 170, 150, 190, 165
      , 170, 165, 111, 165
      , 154, 166, 107, 165
      , 169, 230, 91, 165
      , 170, 233, 91, 165
      , 170, 249, 91, 165
      , 106, 254, 91, 165
      , 154, 255, 86, 85
      , 233, 191, 101, 149
      , 254, 107, 169, 234
      , 191, 86, 249, 255
      , 106, 85, 169, 191
      , 85, 85, 229, 175
      , 170, 170, 250, 255
      
      };
   } satellite_image;
  constexpr uint8_t satellite_image_type::m_data [ 72];

 struct altitude_symbol_type : quan::uav::osd::basic_bitmap{
    uint8_t const * get_data()const
    {
       return m_data;
    }
    quan::uav::osd::size_type get_size()const
    {
       return {21,18};
    }
 private:
    static constexpr uint8_t m_data[95] = {
      255, 175, 170, 254
      , 255, 255, 175, 85
      , 249, 255, 255, 191
      , 165, 150, 255, 255
      , 255, 86, 85, 254
      , 255, 255, 91, 106
      , 249, 255, 255, 191
      , 170, 250, 255, 255
      , 255, 91, 254, 255
      , 255, 255, 111, 249
      , 255, 255, 255, 191
      , 165, 250, 255, 255
      , 255, 86, 149, 255
      , 255, 255, 91, 85
      , 254, 255, 255, 191
      , 170, 234, 255, 255
      , 255, 91, 85, 254
      , 255, 255, 111, 85
      , 249, 255, 255, 255
      , 90, 250, 255, 255
      , 255, 111, 249, 255
      , 255, 255, 191, 229
      , 255, 255, 255, 255
      , 235, 255, 255
      };
   } altitude_symbol;
  constexpr uint8_t altitude_symbol_type::m_data [ 95];

 constexpr quan::uav::osd::bitmap_ptr bitmap_array[] =
   {
    &home_arrow
    ,&home_image
    ,&satellite_image
    ,&altitude_symbol
   };
} // namespace

quan::uav::osd::bitmap_ptr
quan::uav::osd::get_bitmap(uint32_t id)
{
constexpr uint32_t size = sizeof(bitmap_array)/sizeof(quan::uav::osd::bitmap_ptr);
  if ( id < size){
     return bitmap_array[id];
  }else{
     return nullptr;
  }
}
