
//Generated by OSDMaker for the Quantracker Air OSD
//https://github.com/kwikius/quantracker
//https://github.com/kwikius/osd_maker

#include <quan/uav/osd/api.hpp>
#include <quan/uav/osd/basic_bitmap.hpp>

namespace {

 struct compass_arrow_type : quan::uav::osd::basic_bitmap{
    uint8_t const * get_data()const
    {
       return m_data;
    }
    quan::uav::osd::size_type get_size()const
    {
       return {27,30};
    }
 private:
    static constexpr uint8_t m_data[203] = {
      255, 255, 255, 234
      , 255, 255, 255, 255
      , 255, 175, 233, 255
      , 255, 255, 255, 255
      , 91, 249, 255, 255
      , 255, 255, 191, 86
      , 250, 255, 255, 255
      , 255, 111, 85, 254
      , 255, 255, 255, 255
      , 90, 149, 254, 255
      , 255, 255, 191, 21
      , 149, 255, 255, 255
      , 255, 107, 1, 165
      , 255, 255, 255, 255
      , 150, 132, 229, 255
      , 255, 255, 175, 41
      , 161, 233, 255, 255
      , 255, 155, 74, 168
      , 249, 255, 255, 255
      , 170, 18, 170, 254
      , 255, 255, 255, 107
      , 85, 250, 255, 255
      , 171, 255, 150, 90
      , 254, 171, 191, 166
      , 170, 249, 155, 170
      , 166, 111, 85, 85
      , 254, 86, 85, 229
      , 107, 170, 154, 191
      , 169, 106, 250, 171
      , 255, 150, 90, 254
      , 171, 255, 255, 255
      , 86, 229, 255, 255
      , 255, 255, 255, 18
      , 254, 255, 255, 255
      , 255, 191, 132, 255
      , 255, 255, 255, 255
      , 43, 161, 255, 255
      , 255, 255, 191, 70
      , 164, 255, 255, 255
      , 255, 107, 1, 165
      , 255, 255, 255, 191
      , 86, 85, 165, 255
      , 255, 255, 107, 165
      , 106, 165, 255, 255
      , 191, 86, 250, 107
      , 165, 255, 255, 111
      , 165, 255, 107, 229
      , 255, 255, 107, 250
      , 255, 107, 250, 255
      , 255, 171, 255, 255
      , 171, 255, 255
      };
   } compass_arrow;
  constexpr uint8_t compass_arrow_type::m_data [ 203];

 struct home_arrow_type : quan::uav::osd::basic_bitmap{
    uint8_t const * get_data()const
    {
       return m_data;
    }
    quan::uav::osd::size_type get_size()const
    {
       return {15,39};
    }
 private:
    static constexpr uint8_t m_data[147] = {
      255, 191, 255, 255
      , 255, 171, 255, 255
      , 191, 166, 255, 255
      , 111, 229, 255, 255
      , 26, 233, 255, 191
      , 69, 249, 255, 107
      , 64, 250, 255, 22
      , 80, 254, 175, 1
      , 144, 254, 91, 0
      , 148, 191, 6, 0
      , 164, 111, 1, 0
      , 229, 91, 5, 84
      , 249, 170, 1, 169
      , 254, 111, 64, 254
      , 255, 27, 144, 255
      , 255, 6, 228, 255
      , 191, 1, 249, 255
      , 111, 64, 254, 255
      , 27, 144, 255, 255
      , 6, 228, 255, 191
      , 1, 249, 255, 111
      , 64, 254, 255, 27
      , 144, 255, 255, 6
      , 228, 255, 191, 1
      , 249, 255, 111, 64
      , 254, 255, 27, 144
      , 255, 255, 6, 228
      , 255, 175, 1, 233
      , 255, 90, 64, 233
      , 191, 5, 64, 249
      , 111, 80, 65, 254
      , 26, 101, 145, 190
      , 69, 106, 148, 107
      , 149, 90, 165, 86
      , 234, 106, 165, 170
      , 255, 171, 250, 255
      , 255, 255, 255
      };
   } home_arrow;
  constexpr uint8_t home_arrow_type::m_data [ 147];

 struct home_image_type : quan::uav::osd::basic_bitmap{
    uint8_t const * get_data()const
    {
       return m_data;
    }
    quan::uav::osd::size_type get_size()const
    {
       return {20,19};
    }
 private:
    static constexpr uint8_t m_data[95] = {
      255, 255, 235, 255
      , 255, 255, 191, 150
      , 254, 255, 255, 107
      , 105, 233, 255, 191
      , 150, 150, 150, 254
      , 107, 105, 85, 105
      , 233, 150, 86, 85
      , 149, 150, 106, 85
      , 85, 85, 169, 111
      , 85, 149, 170, 249
      , 111, 85, 149, 128
      , 249, 111, 169, 154
      , 128, 249, 111, 9
      , 152, 128, 249, 111
      , 9, 152, 128, 249
      , 111, 9, 152, 170
      , 249, 111, 9, 88
      , 85, 249, 111, 9
      , 88, 85, 249, 111
      , 9, 88, 85, 249
      , 111, 9, 88, 85
      , 249, 111, 9, 88
      , 85, 249, 175, 170
      , 170, 170, 250
      };
   } home_image;
  constexpr uint8_t home_image_type::m_data [ 95];

 struct satellite_image_type : quan::uav::osd::basic_bitmap{
    uint8_t const * get_data()const
    {
       return m_data;
    }
    quan::uav::osd::size_type get_size()const
    {
       return {15,19};
    }
 private:
    static constexpr uint8_t m_data[72] = {
      175, 234, 255, 255
      , 90, 233, 175, 175
      , 169, 229, 150, 91
      , 170, 166, 229, 150
      , 170, 150, 190, 165
      , 170, 165, 111, 165
      , 154, 166, 107, 165
      , 169, 230, 91, 165
      , 170, 233, 91, 165
      , 170, 249, 91, 165
      , 106, 254, 91, 165
      , 154, 255, 86, 85
      , 233, 191, 101, 149
      , 254, 107, 169, 234
      , 191, 86, 249, 255
      , 106, 85, 169, 191
      , 85, 85, 229, 175
      , 170, 170, 250, 255
      
      };
   } satellite_image;
  constexpr uint8_t satellite_image_type::m_data [ 72];

 struct altitude_symbol_type : quan::uav::osd::basic_bitmap{
    uint8_t const * get_data()const
    {
       return m_data;
    }
    quan::uav::osd::size_type get_size()const
    {
       return {21,18};
    }
 private:
    static constexpr uint8_t m_data[95] = {
      255, 175, 170, 254
      , 255, 255, 175, 85
      , 249, 255, 255, 191
      , 165, 150, 255, 255
      , 255, 86, 85, 254
      , 255, 255, 91, 106
      , 249, 255, 255, 191
      , 170, 250, 255, 255
      , 255, 91, 254, 255
      , 255, 255, 111, 249
      , 255, 255, 255, 191
      , 165, 250, 255, 255
      , 255, 86, 149, 255
      , 255, 255, 91, 85
      , 254, 255, 255, 191
      , 170, 234, 255, 255
      , 255, 91, 85, 254
      , 255, 255, 111, 85
      , 249, 255, 255, 255
      , 90, 250, 255, 255
      , 255, 111, 249, 255
      , 255, 255, 191, 229
      , 255, 255, 255, 255
      , 235, 255, 255
      };
   } altitude_symbol;
  constexpr uint8_t altitude_symbol_type::m_data [ 95];

 constexpr quan::uav::osd::bitmap_ptr bitmap_array[] =
   {
    &compass_arrow
    ,&home_arrow
    ,&home_image
    ,&satellite_image
    ,&altitude_symbol
   };
} // namespace

quan::uav::osd::bitmap_ptr
quan::uav::osd::get_bitmap(uint32_t id)
{
constexpr uint32_t size = sizeof(bitmap_array)/sizeof(quan::uav::osd::bitmap_ptr);
  if ( id < size){
     return bitmap_array[id];
  }else{
     return nullptr;
  }
}
