#ifndef USER_BITMAP_HPP_INCLUDED
#define USER_BITMAP_HPP_INCLUDED

//Generated by OSDMaker

#include <quan/uav/osd/basic_bitmap.hpp>

 struct BitmapID{
static constexpr uint32_t compass_arrow = 0;
static constexpr uint32_t home_arrow = 1;
static constexpr uint32_t home_image = 2;
static constexpr uint32_t satellite_image = 3;
static constexpr uint32_t altitude_symbol = 4;
};

#endif
