#ifndef QUANTRACKER_USER_BITMAP_AERFLITE_BITMAPS_1475506715_HPP_INCLUDED
#define QUANTRACKER_USER_BITMAP_AERFLITE_BITMAPS_1475506715_HPP_INCLUDED
//Generated by OSDMaker for the Quantracker Air OSD

//https://github.com/kwikius/quantracker
//https://github.com/kwikius/osd_maker
#include <quan/uav/osd/basic_bitmap.hpp>

   struct BitmapID{
      static constexpr uint32_t home_image = 0;
      static constexpr uint32_t satellite_image = 1;
      static constexpr uint32_t altitude_symbol = 2;
      static constexpr uint32_t home_arrow = 3;
   };

#endif // QUANTRACKER_USER_BITMAP_AERFLITE_BITMAPS_1475506715_HPP_INCLUDED
