#ifndef QUANTRACKER_USER_FONT_FONT_1436788130_HPP_INCLUDED
#define QUANTRACKER_USER_FONT_FONT_1436788130_HPP_INCLUDED


//Generated by OSDMaker for the Quantracker Air OSD
//https://github.com/kwikius/quantracker
//https://github.com/kwikius/osd_maker
#include <quan/uav/osd/basic_font.hpp>

   struct FontID{
      static constexpr uint32_t OSD_Charset = 0;
};

#endif // QUANTRACKER_USER_FONT_FONT_1436788130_HPP_INCLUDED
