#ifndef QUANTRACKER_AIR_OSD_RX_TELEMETRY_HPP_INCLUDED
#define QUANTRACKER_AIR_OSD_RX_TELEMETRY_HPP_INCLUDED


#include <quantracker/osd/telemetry_receiver.hpp>

#endif // QUANTRACKER_AIR_OSD_TELEMETRY_HPP_INCLUDED
