#ifndef QUANTRACKER_EXAMPLES_OSD_TELEM_TX_APPLICATION_HPP_INCLUDED
#define QUANTRACKER_EXAMPLES_OSD_TELEM_TX_APPLICATION_HPP_INCLUDED

extern "C" void setup();
void create_tasks();
void start_scheduler();

#endif // QUANTRACKER_EXAMPLES_OSD_TELEM_TX_APPLICATION_HPP_INCLUDED
