#ifndef QUANTRACKER_USER_BITMAP_BITMAP_1438865310_HPP_INCLUDED
#define QUANTRACKER_USER_BITMAP_BITMAP_1438865310_HPP_INCLUDED
//Generated by OSDMaker for the Quantracker Air OSD

//https://github.com/kwikius/quantracker
//https://github.com/kwikius/osd_maker
#include <quan/uav/osd/basic_bitmap.hpp>

   struct BitmapID{
      static constexpr uint32_t home_arrow = 0;
      static constexpr uint32_t home_image = 1;
      static constexpr uint32_t satellite_image = 2;
      static constexpr uint32_t altitude_symbol = 3;
   };

#endif // QUANTRACKER_USER_BITMAP_BITMAP_1438865310_HPP_INCLUDED
